In [19]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

In [7]:
columns = ['V2AF13', 'V2AF15', 'PublicID']
df_temp = pd.read_csv('V2A.csv', usecols=columns)
df_out = pd.read_csv('Outcome.csv',usecols=['V4AH01','PublicID'])
df_out = df_out[df_out != 'D']

In [9]:
df_out

     PublicID  V4AH01
0      00004O     3.0
1      00007I     2.0
2      00008G     3.0
3      00015J     NaN
4      00016H     NaN
...       ...     ...
7736   17349I     NaN
7737   17350A     NaN
7738   17351V     NaN
7739   17352T     3.0
7740   17354P     NaN

[7741 rows x 2 columns]

In [23]:
# df_out['CBAA04b'] = df_out['CBAA04b'].astype(float)
# df_out['CBAA04a'] = df_out['CBAA04a'].astype(float)

In [24]:
df_out

,PublicID,MH_outcome,Birth_Weight_Category,CBAA04a,CBAA04b,Birth_Type,Preterm_Birth_Category,V4AH01
0,00004O,1,3.0,8.0,9.0,1,3,3.0
1,00007I,1,3.0,9.0,9.0,1,3,2.0
2,00008G,0,3.0,8.0,9.0,1,3,3.0
3,00015J,0,3.0,9.0,9.0,1,3,NaN
4,00016H,1,3.0,3.0,8.0,1,3,NaN
...,...,...,...,...,...,...,...,...
7736,17349I,1,NaN,6.0,8.0,1,3,NaN
7737,17350A,1,2.0,7.0,9.0,1,2,NaN
7738,17351V,0,3.0,9.0,9.0,1,3,NaN
7739,17352T,1,3.0,9.0,9.0,1,3,3.0
7740,17354P,1,3.0,9.0,9.0,1,3,NaN

In [25]:
# df_out['CBAA04a'] = df_out['CBAA04a'].apply(lambda x: 0 if x < 7 else 1)
# df_out['CBAA04b'] = df_out['CBAA04b'].apply(lambda x: 0 if x < 7 else 1)

In [26]:
# df_out = df_out[df_out != 'D']

print(df_out.dtypes)

PublicID                   object
MH_outcome                  int64
Birth_Weight_Category     float64
CBAA04a                     int64
CBAA04b                     int64
Birth_Type                  int64
Preterm_Birth_Category      int64
V4AH01                    float64
dtype: object

In [27]:
# df_temp = df_temp.dropna()
df_out['MH_outcome'].value_counts()

0    4591
1    3150
Name: MH_outcome, dtype: int64

In [15]:
df

     PublicID V2AF13 V2AF15  V4AH01
0      00004O     26      5     3.0
1      00007I     39      3     2.0
2      00008G     32      3     3.0
5      00017F     35      6     1.0
9      00023K     23      2     1.0
...       ...    ...    ...     ...
7598   17339L     27      6     1.0
7599   17340D     22      4     1.0
7601   17343U     31      6     1.0
7602   17345Q     30      6     1.0
7606   17352T     31      6     3.0

[4307 rows x 4 columns]

In [29]:
df = pd.merge(df_temp, df_out, on='PublicID', how='inner')

In [14]:
df['V2AF13'].value_counts()

V2AF13
30    324
32    301
31    281
28    275
29    274
27    260
26    240
33    234
24    226
25    219
34    204
23    191
35    171
36    145
22    128
37    114
21    113
20    106
38     80
19     77
18     56
40     53
39     40
41     36
42     26
17     21
43     20
45     16
44     14
47     13
46     11
16      7
49      7
50      5
48      5
15      3
59      2
52      2
70      2
58      1
55      1
57      1
13      1
69      1
Name: count, dtype: int64

In [31]:
df = df[df != 'R']
df = df[df != 'D']
df = df.dropna()

In [30]:
df

     PublicID V2AF13 V2AF15  V4AH01
0      00004O     26      5     3.0
1      00007I     39      3     2.0
2      00008G     32      3     3.0
3      00015J     33      6     NaN
4      00016H     29      3     NaN
...       ...    ...    ...     ...
7603   17349I     25      5     NaN
7604   17350A     38      3     NaN
7605   17351V     32      6     NaN
7606   17352T     31      6     3.0
7607   17354P     19      3     NaN

[7608 rows x 4 columns]

In [32]:
# df = df.drop(['PublicID'],axis=1)
one_hot_encoded = pd.get_dummies(df['V2AF15'], prefix='V2AF15')
df = df.join(one_hot_encoded)
scaler = StandardScaler()
df['V2AF13'] = scaler.fit_transform(df[['V2AF13']])

,V2AF15,V4AH01,V2AF15_1,V2AF15_2,V2AF15_3,V2AF15_4,V2AF15_5,V2AF15_6,V2AF15_7,V2AF15_8
0,5,3.0,False,False,False,False,True,False,False,False
1,3,2.0,False,False,True,False,False,False,False,False
2,3,3.0,False,False,True,False,False,False,False,False
5,6,1.0,False,False,False,False,False,True,False,False
9,2,1.0,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
7598,6,1.0,False,False,False,False,False,True,False,False
7599,4,1.0,False,False,False,True,False,False,False,False
7601,6,1.0,False,False,False,False,False,True,False,False
7602,6,1.0,False,False,False,False,False,True,False,False
7606,6,3.0,False,False,False,False,False,True,False,False

In [39]:
X = df.drop(['V4AH01','PublicID','V2AF15'], axis=1)
y = df['V4AH01']

In [41]:
X

,V2AF13,V2AF15_1,V2AF15_2,V2AF15_3,V2AF15_4,V2AF15_5,V2AF15_6,V2AF15_7,V2AF15_8
0,-0.567365,False,False,False,False,True,False,False,False
1,1.593384,False,False,True,False,False,False,False,False
2,0.429904,False,False,True,False,False,False,False,False
5,0.928538,False,False,False,False,False,True,False,False
9,-1.065999,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
7598,-0.401153,False,False,False,False,False,True,False,False
7599,-1.232210,False,False,False,True,False,False,False,False
7601,0.263692,False,False,False,False,False,True,False,False
7602,0.097481,False,False,False,False,False,True,False,False
7606,0.263692,False,False,False,False,False,True,False,False

In [33]:
# from sklearn.preprocessing import StandardScaler

# # # Create a StandardScaler instance
# standard_scaler = StandardScaler()

# X_scaled = standard_scaler.fit_transform(X)
# X = pd.DataFrame(X_scaled, columns=['V2AF13','V2AF15'])

In [34]:
# from sklearn.preprocessing import MinMaxScaler

# min_max_scaler = MinMaxScaler()
# column_names = X.columns

# X = pd.DataFrame(min_max_scaler.fit_transform(X), columns=column_names)

In [35]:
y.value_counts()

MH_outcome
0             4403
1             2950
dtype: int64

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)

model = LogisticRegression(solver='liblinear')

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Model Coefficients:")
for feature, coef in zip(X.columns, model.coef_[0]):
    print(f"{feature}: {coef}")

Model Coefficients:
V2AF13: -0.015683328289162444
V2AF15_1: -0.5261498415519279
V2AF15_2: -2.3592419269817615
V2AF15_3: -1.4763910035440073
V2AF15_4: -0.7451798999513212
V2AF15_5: -0.7223484887354763
V2AF15_6: -0.39499663864100726
V2AF15_7: -0.3984030554743506
V2AF15_8: -0.1852982905040774

In [44]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
# roc_auc = roc_auc_score(y_test, y_pred)

print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
# print(f"ROC AUC: {roc_auc:.4f}")

Evaluation Metrics:
Accuracy: 0.5464
Precision: 0.5181
Recall: 0.5464
F1-score: 0.5060

In [38]:
rf_model = RandomForestClassifier(random_state=42)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)

print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

C:\Users\91799\AppData\Local\Temp\ipykernel_21996\2479386719.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_model.fit(X_train, y_train)

Evaluation Metrics:
Accuracy: 0.5411
Precision: 0.4448
Recall: 0.4368
F1-score: 0.4408
ROC AUC: 0.5258

In [39]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

# Define the XGBoost model
model = XGBClassifier()

# Define hyperparameters to search
param_grid = {
    'learning_rate': [0.01, 0.05, 0.001],
    'n_estimators': [100, 80, 60],
    'max_depth': [7, 4, 6],
    'subsample': [0.8, 0.7, 0.5],
    'colsample_bytree': [0.8, 0.9, 1.0]
}

# Perform GridSearchCV
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='roc_auc')
grid_result = grid_search.fit(X_train, y_train)

# Print the best parameters and score
print("Best Hyperparameters: ", grid_result.best_params_)
print("Best ROC AUC Score: ", grid_result.best_score_)

# Use the best model
best_model = grid_result.best_estimator_
 
y_pred_prob = best_model.predict_proba(X_test)
# y_pred = np.where(y_pred_prob[:, 1] >= 0.5, 1, 0)

y_pred = [1 if prob[1] >= 0.4 else 0 for prob in y_pred_prob]

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)

print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

Best Hyperparameters:  {'colsample_bytree': 0.8, 'learning_rate': 0.001, 'max_depth': 6, 'n_estimators': 80, 'subsample': 0.8}
Best ROC AUC Score:  0.5813698850828378
Evaluation Metrics:
Accuracy: 0.4140
Precision: 0.4140
Recall: 1.0000
F1-score: 0.5856
ROC AUC: 0.5000

In [40]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from imblearn.over_sampling import SMOTE

columns = ['V2AF13', 'V2AF15', 'PublicID']
df_temp = pd.read_csv('V2A.csv', usecols=columns)
df_temp = df_temp[df_temp != 'D']
df_temp = df_temp[df_temp != 'R']
df_temp = df_temp.dropna()

df_mental = pd.read_excel('Outcomes_mental.xlsx')
# df_mental = df_mental[df_mental != 'D']
# df_mental = df_mental[df_mental != 'R']
df_mental = df_mental.dropna()

# Merge the dataframes
# df_out = df_out.rename(columns={'CBAA04a': 'CBAA04a_outcome', 'CBAA04b': 'CBAA04b_outcome'})
df_1 = pd.merge(df_temp, df_mental, on='PublicID', how='inner')

# Prepare the features (X) and target (y)
X = df_1.drop(['MH_outcome', 'PublicID'], axis=1)
y = df_1['MH_outcome']

# Standardize the features
standard_scaler = StandardScaler()
X_scaled = standard_scaler.fit_transform(X)
X = pd.DataFrame(X_scaled, columns=X.columns)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply SMOTE
smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)

# Fit the model
model = LogisticRegression(solver='liblinear')
model.fit(X_train, y_train)

param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear', 'saga']  # 'liblinear' and 'saga' work well with l1 and l2 penalties
}

# Set up GridSearchCV
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy', verbose=1, n_jobs=-1)

# Perform grid search
grid_search.fit(X_train, y_train)

# Best parameters
print("Best parameters found: ", grid_search.best_params_)
best_model = grid_search.best_estimator_

# Make predictions with the best model
y_pred = best_model.predict(X_test)

# Make predictions and evaluate the model
# y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
roc_auc = roc_auc_score(y_test, y_pred)

# Print the results
print("Model Coefficients:")
for feature, coef in zip(X.columns, model.coef_[0]):
    print(f"{feature}: {coef}")

print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

Fitting 5 folds for each of 24 candidates, totalling 120 fits
Best parameters found:  {'C': 1, 'penalty': 'l1', 'solver': 'saga'}
Model Coefficients:
V2AF13: -0.03938354500530181
V2AF15: -0.25439599204667496
Evaluation Metrics:
Accuracy: 0.5452
Precision: 0.5566
Recall: 0.5452
F1-score: 0.5484
ROC AUC: 0.5433

In [41]:
df_bf = pd.read_excel('Outcomes_breastfeeding.xlsx')
df_bf = df_bf.dropna()

# Merge the dataframes
df_2 = pd.merge(df_temp, df_bf, on='PublicID', how='inner')

# Prepare the features (X) and target (y)
X = df_2.drop(['V4AH01', 'PublicID'], axis=1)
y = df_2['V4AH01']

# Standardize the features
standard_scaler = StandardScaler()
X_scaled = standard_scaler.fit_transform(X)
X = pd.DataFrame(X_scaled, columns=X.columns)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply SMOTE
smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)

# Fit the model
model = LogisticRegression(solver='liblinear')
model.fit(X_train, y_train)

param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear', 'saga']  # 'liblinear' and 'saga' work well with l1 and l2 penalties
}

# Set up GridSearchCV
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy', verbose=1, n_jobs=-1)

# Perform grid search
grid_search.fit(X_train, y_train)

# Best parameters
print("Best parameters found: ", grid_search.best_params_)
best_model = grid_search.best_estimator_

# Make predictions with the best model
y_pred = best_model.predict(X_test)

# Make predictions and evaluate the model
# y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
# roc_auc = roc_auc_score(y_test, y_pred)

# Print the results
print("Model Coefficients:")
for feature, coef in zip(X.columns, model.coef_[0]):
    print(f"{feature}: {coef}")

print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
# print(f"ROC AUC: {roc_auc:.4f}")

Fitting 5 folds for each of 24 candidates, totalling 120 fits
Best parameters found:  {'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}
Model Coefficients:
V2AF13: -0.00998112219842369
V2AF15: 0.5184881187100041
Evaluation Metrics:
Accuracy: 0.4698
Precision: 0.5636
Recall: 0.4698
F1-score: 0.4864

In [45]:
y.value_counts()

V4AH01
1.0    2702
3.0    1135
2.0     470
Name: count, dtype: int64