In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("V2A.csv", usecols=['V2AH01','V2AH02','V2AH03','V2AH04','V2AH05','V2AH06','PublicID'])

C:\Users\91799\AppData\Local\Temp\ipykernel_20008\3052999014.py:4: DtypeWarning: Columns (258,262,266,267,268,269) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("V2A.csv", usecols=['V2AH01','V2AH02','V2AH03','V2AH04','V2AH05','V2AH06','PublicID'])

In [3]:
df = df.dropna()
df = df[df != 'R']

In [4]:
df['V2AH01'] = df['V2AH01'].astype(float)
df['V2AH02'] = df['V2AH02'].astype(float)
df['V2AH03'] = df['V2AH03'].astype(float)
df['V2AH04'] = df['V2AH04'].astype(float)
df['V2AH05'] = df['V2AH05'].astype(float)
df['V2AH06'] = df['V2AH06'].astype(float)

# df['V2AH01'].value_counts()

In [5]:
df

     PublicID  V2AH01  V2AH02  V2AH03  V2AH04  V2AH05  V2AH06
0      00004O     2.0     2.0     2.0     2.0     2.0     2.0
1      00007I     2.0     1.0     2.0     2.0     2.0     2.0
2      00008G     2.0     2.0     2.0     2.0     2.0     2.0
3      00015J     2.0     2.0     2.0     2.0     2.0     2.0
4      00016H     2.0     2.0     2.0     2.0     2.0     2.0
...       ...     ...     ...     ...     ...     ...     ...
8729   17349I     2.0     2.0     2.0     2.0     2.0     2.0
8730   17350A     2.0     2.0     2.0     2.0     2.0     2.0
8731   17351V     2.0     2.0     2.0     2.0     2.0     2.0
8732   17352T     2.0     2.0     2.0     2.0     2.0     2.0
8733   17354P     2.0     2.0     2.0     2.0     2.0     2.0

[8696 rows x 7 columns]

In [6]:
### df['V2AH01'].replace('', np.nan, inplace=True)

In [7]:
df_out = pd.read_csv('outcome.csv',usecols=['PublicID','MH_outcome'])
df = pd.merge(df, df_out, on='PublicID', how='inner')

In [8]:
df = df.dropna()

In [61]:
X = df.drop(['PublicID','MH_outcome'],axis=1)
# y = df['V4AH01']

In [62]:
y = df['MH_outcome']

In [10]:
df_drugs = df
%store df_drugs

Stored 'df_drugs' (DataFrame)

In [8]:
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()

# X_scaled = scaler.fit_transform(X)

# X = pd.DataFrame(X_scaled, columns=X.columns)

In [64]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
# from imblearn.over_sampling import SMOTE


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)
# smote = SMOTE(random_state=42)
# X_train, y_train = smote.fit_resample(X_train, y_train)

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Model Coefficients:")
for feature, coef in zip(X.columns, model.coef_[0]):
    print(f"{feature}: {coef}")

Model Coefficients:
V2AH01: -0.1466477076075126
V2AH02: -0.9519558268509497
V2AH03: -0.674005320844406
V2AH04: -0.886280941909063
V2AH05: -0.5975843476301215
V2AH06: -0.7236260417694442

In [65]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Compute evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
# roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])

# Print the evaluation metrics
print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
# print(f"ROC AUC: {roc_auc:.4f}")

Evaluation Metrics:
Accuracy: 0.6222
Precision: 0.6211
Recall: 0.6222
F1-score: 0.5210

In [16]:
X

      V2AH01  V2AH02  V2AH03  V2AH04  V2AH06
0        2.0     2.0     2.0     2.0     2.0
1        2.0     1.0     2.0     2.0     2.0
2        2.0     2.0     2.0     2.0     2.0
5        2.0     2.0     2.0     2.0     2.0
10       2.0     1.0     2.0     2.0     2.0
...      ...     ...     ...     ...     ...
8686     2.0     2.0     2.0     2.0     2.0
8687     2.0     2.0     2.0     2.0     2.0
8689     2.0     2.0     2.0     2.0     2.0
8690     2.0     2.0     2.0     2.0     2.0
8694     2.0     2.0     2.0     2.0     2.0

[4424 rows x 5 columns]

==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c defaults conda

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\91799\anaconda3

  added / updated specs:
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aiobotocore-2.7.0          |   py39haa95532_0         118 KB
    aiohttp-3.9.3              |   py39h2bbff1b_0         660 KB
    anaconda-anon-usage-0.4.4  |   py39h8ddfbff_0          27 KB
    anaconda-client-1.12.3     |   py39haa95532_0         171 KB
    anyio-4.2.0                |   py39haa95532_0         186 KB
    aom-3.6.0                  |       hd77b12b_0         9.1 MB
    astropy-5.3.4              |   py39h9128911_0         8.1 MB
    async-lru-2.0.4            |   py39haa95532_0          18 KB
    async-timeout-4.0.3        |   py39haa95532_0          13 KB
    attrs-23.1.0               |   py39haa95532_0         143 KB
    autopep8-2.0.4             |     pyhd3eb1b0_0          44 KB
    black-23.11.0              |   py39haa95532_0         289 KB
    bokeh-3.3.4                |   py39h9909e9c_0         5.4 MB
    botocore-1.31.64           |   py39haa95532_0         6.8 MB
    bottleneck-1.3.7           |   py39h9128911_0         115 KB
    brotli-python-1.0.9        |   py39hd77b12b_7         309 KB
    bzip2-1.0.8                |       h2bbff1b_5          78 KB
    c-blosc2-2.12.0            |       h2f4ed9d_0         222 KB
    ca-certificates-2024.3.11  |       haa95532_0         128 KB
    certifi-2024.2.2           |   py39haa95532_0         160 KB
    cffi-1.16.0                |   py39h2bbff1b_0         242 KB
    click-8.1.7                |   py39haa95532_0         164 KB
    colorcet-3.1.0             |   py39haa95532_0         564 KB
    comm-0.2.1                 |   py39haa95532_0          15 KB
    conda-package-handling-2.2.0|   py39haa95532_0         287 KB
    conda-package-streaming-0.9.0|   py39haa95532_0          29 KB
    conda-repo-cli-1.0.88      |   py39haa95532_0         154 KB
    constantly-23.10.4         |   py39haa95532_0          27 KB
    contourpy-1.2.0            |   py39h59b6b97_0         202 KB
    cookiecutter-2.6.0         |   py39haa95532_0         144 KB
    cssselect-1.2.0            |   py39haa95532_0          38 KB
    curl-8.5.0                 |       he2ea4bf_0         156 KB
    cytoolz-0.12.2             |   py39h2bbff1b_0         311 KB
    dal-2023.1.1               |   h59b6b97_48682        26.5 MB
    dask-2022.2.1              |     pyhd3eb1b0_0           5 KB
    dask-core-2022.2.1         |     pyhd3eb1b0_0         747 KB
    datashader-0.16.0          |   py39haa95532_0        16.9 MB
    dav1d-1.2.1                |       h2bbff1b_0         672 KB
    debugpy-1.6.7              |   py39hd77b12b_0         2.9 MB
    dill-0.3.7                 |   py39haa95532_0         189 KB
    distributed-2022.2.1       |     pyhd3eb1b0_0         659 KB
    exceptiongroup-1.2.0       |   py39haa95532_0          30 KB
    filelock-3.13.1            |   py39haa95532_0          21 KB
    flake8-7.0.0               |   py39haa95532_0         112 KB
    flask-2.2.5                |   py39haa95532_0         167 KB
    frozenlist-1.4.0           |   py39h2bbff1b_0          46 KB
    fsspec-2023.10.0           |   py39haa95532_0         264 KB
    glib-2.78.4                |       hd77b12b_0         491 KB
    glib-tools-2.78.4          |       hd77b12b_0          91 KB
    gmpy2-2.1.2                |   py39h7f96b67_0         160 KB
    greenlet-3.0.1             |   py39hd77b12b_0         195 KB
    h5py-3.9.0                 |   py39hfc34f40_0         914 KB
    hdf5-1.12.1                |       h51c971a_3        11.9 MB
    holoviews-1.18.3           |   py39haa95532_0         4.5 MB
    huggingface_hub-0.20.3     |   py39haa95532_0         404 KB
    hvplot-0.9.2               |   py39haa95532_0         1.8 MB
    imagecodecs-2023.1.23      |   py39h6c6a46e_0         8.9 MB
    imageio-2.33.1             |   py39haa95532_0         488 KB
    imbalanced-learn-0.11.0    |   py39haa95532_1         292 KB
    importlib-metadata-7.0.1   |   py39haa95532_0          41 KB
    importlib_metadata-7.0.1   |       hd3eb1b0_0           8 KB
    importlib_resources-6.1.1  |   py39haa95532_1          55 KB
    incremental-22.10.0        |     pyhd3eb1b0_0          18 KB
    intel-openmp-2023.1.0      |   h59b6b97_46320         2.7 MB
    ipykernel-6.28.0           |   py39haa95532_0         197 KB
    ipython-8.15.0             |   py39haa95532_0         1.1 MB
    ipywidgets-8.1.2           |   py39haa95532_0         197 KB
    itemloaders-1.1.0          |   py39haa95532_0          28 KB
    jellyfish-1.0.1            |   py39h36a85e1_0         214 KB
    jinja2-3.1.3               |   py39haa95532_0         271 KB
    jmespath-1.0.1             |   py39haa95532_0          40 KB
    jsonschema-4.19.2          |   py39haa95532_0         164 KB
    jsonschema-specifications-2023.7.1|   py39haa95532_0          16 KB
    jupyter-1.0.0              |   py39haa95532_9           8 KB
    jupyter-lsp-2.2.0          |   py39haa95532_0          87 KB
    jupyter_client-8.6.0       |   py39haa95532_0         202 KB
    jupyter_core-5.5.0         |   py39haa95532_0          97 KB
    jupyter_events-0.8.0       |   py39haa95532_0          52 KB
    jupyter_server-2.10.0      |   py39haa95532_0         497 KB
    jupyterlab-4.0.11          |   py39haa95532_0         4.5 MB
    jupyterlab_server-2.25.1   |   py39haa95532_0          88 KB
    jupyterlab_widgets-3.0.10  |   py39haa95532_0         196 KB
    keyring-24.3.1             |   py39haa95532_0          84 KB
    lazy_loader-0.3            |   py39haa95532_0          18 KB
    libavif-0.11.1             |       h2bbff1b_0         1.9 MB
    libcurl-8.5.0              |       h86230a5_0         343 KB
    libdeflate-1.17            |       h2bbff1b_1         153 KB
    libglib-2.78.4             |       ha17d25a_0         1.3 MB
    libtiff-4.5.1              |       hd77b12b_0         1.1 MB
    libwebp-base-1.3.2         |       h2bbff1b_0         306 KB
    libxml2-2.10.4             |       h0ad7f3c_1         2.8 MB
    libxslt-1.1.37             |       h2bbff1b_1         447 KB
    llvmlite-0.42.0            |   py39hf2fb9eb_0        18.6 MB
    lxml-4.9.3                 |   py39h09808a7_0         1.1 MB
    markupsafe-2.1.3           |   py39h2bbff1b_0          25 KB
    mistune-2.0.4              |   py39haa95532_0          93 KB
    mkl-2023.1.0               |   h6b88ed4_46358       155.9 MB
    mkl_fft-1.3.8              |   py39h2bbff1b_0         169 KB
    mkl_random-1.2.4           |   py39h59b6b97_0         228 KB
    more-itertools-10.1.0      |   py39haa95532_0          85 KB
    mpc-1.1.0                  |       h7edee0f_1         260 KB
    mpfr-4.0.2                 |       h62dcd97_1         1.5 MB
    mpir-3.0.0                 |       hec2e145_1         1.3 MB
    mpmath-1.3.0               |   py39haa95532_0         828 KB
    multidict-6.0.4            |   py39h2bbff1b_0          50 KB
    mypy_extensions-1.0.0      |   py39haa95532_0          12 KB
    nbclient-0.8.0             |   py39haa95532_0         115 KB
    nbconvert-7.10.0           |   py39haa95532_0         491 KB
    nbformat-5.9.2             |   py39haa95532_0         155 KB
    nest-asyncio-1.6.0         |   py39haa95532_0          15 KB
    networkx-3.1               |   py39haa95532_0         2.7 MB
    notebook-7.0.8             |   py39haa95532_0         3.4 MB
    notebook-shim-0.2.3        |   py39haa95532_0          23 KB
    numba-0.59.1               |   py39hd77b12b_0         4.4 MB
    numexpr-2.8.7              |   py39h2cd9be0_0         132 KB
    numpy-1.26.4               |   py39h055cbcc_0          11 KB
    numpy-base-1.26.4          |   py39h65a83cf_0         8.5 MB
    openssl-1.1.1w             |       h2bbff1b_0         5.5 MB
    overrides-7.4.0            |   py39haa95532_0          30 KB
    packaging-23.2             |   py39haa95532_0         148 KB
    pandas-2.1.4               |   py39h4ed8f06_0        11.0 MB
    panel-1.3.8                |   py39haa95532_0        14.9 MB
    param-2.1.0                |   py39haa95532_0         200 KB
    parsel-1.8.1               |   py39haa95532_0          45 KB
    partd-1.4.1                |   py39haa95532_0          37 KB
    pcre2-10.42                |       h0ff8eda_0         739 KB
    pillow-10.2.0              |   py39h2bbff1b_0         797 KB
    pip-23.3.1                 |   py39haa95532_0         2.8 MB
    platformdirs-3.10.0        |   py39haa95532_0          35 KB
    plotly-5.19.0              |   py39h9909e9c_0         6.0 MB
    prompt-toolkit-3.0.43      |   py39haa95532_0         572 KB
    prompt_toolkit-3.0.43      |       hd3eb1b0_0           5 KB
    py-cpuinfo-9.0.0           |   py39haa95532_0          61 KB
    pycodestyle-2.11.1         |   py39haa95532_0          71 KB
    pycosat-0.6.6              |   py39h2bbff1b_0          84 KB
    pyflakes-3.2.0             |   py39haa95532_0         139 KB
    pylint-venv-3.0.3          |   py39haa95532_0          12 KB
    pyodbc-5.0.1               |   py39hd77b12b_0          66 KB
    pyopenssl-23.2.0           |   py39haa95532_0          96 KB
    pyqt-5.15.10               |   py39hd77b12b_0         4.1 MB
    pyqt5-sip-12.13.0          |   py39h2bbff1b_0          75 KB
    pyqtwebengine-5.15.10      |   py39hd77b12b_0         134 KB
    pytables-3.9.2             |   py39hcff0796_0         1.2 MB
    pytest-7.4.0               |   py39haa95532_0         539 KB
    python-lsp-black-2.0.0     |   py39haa95532_0          15 KB
    python-lsp-jsonrpc-1.1.2   |     pyhd3eb1b0_0          12 KB
    python-lsp-server-1.10.0   |   py39haa95532_0         138 KB
    python-tzdata-2023.3       |     pyhd3eb1b0_0         140 KB
    pytoolconfig-1.2.6         |   py39haa95532_0          31 KB
    pytz-2023.3.post1          |   py39haa95532_0         210 KB
    pyviz_comms-3.0.2          |   py39haa95532_0          54 KB
    pywavelets-1.5.0           |   py39h9128911_0         3.6 MB
    pywin32-ctypes-0.2.2       |   py39haa95532_0          44 KB
    pyyaml-6.0.1               |   py39h2bbff1b_0         160 KB
    pyzmq-25.1.2               |   py39hd77b12b_0         411 KB
    qdarkstyle-3.2.3           |     pyhd3eb1b0_0         615 KB
    qt-webengine-5.15.9        |       h5bd16bc_7        58.1 MB
    qtconsole-5.5.1            |   py39haa95532_0         210 KB
    qtpy-2.4.1                 |   py39haa95532_0         126 KB
    queuelib-1.6.2             |   py39haa95532_0          28 KB
    referencing-0.30.2         |   py39haa95532_0          62 KB
    regex-2023.10.3            |   py39h2bbff1b_0         326 KB
    requests-2.31.0            |   py39haa95532_1          98 KB
    requests-toolbelt-1.0.0    |   py39haa95532_0          71 KB
    rich-13.3.5                |   py39haa95532_0         407 KB
    rope-1.12.0                |   py39haa95532_0         451 KB
    rpds-py-0.10.6             |   py39h062c2fa_0         202 KB
    s3fs-2023.10.0             |   py39haa95532_0          55 KB
    safetensors-0.4.2          |   py39h0010962_0         284 KB
    scikit-image-0.22.0        |   py39h25bd2df_0         9.6 MB
    scikit-learn-1.3.0         |   py39h4ed8f06_1         7.0 MB
    scipy-1.12.0               |   py39h8640f81_0        25.6 MB
    scrapy-2.11.1              |   py39haa95532_0         730 KB
    send2trash-1.8.2           |   py39haa95532_0          76 KB
    setuptools-68.2.2          |   py39haa95532_0         933 KB
    sip-6.7.12                 |   py39hd77b12b_0         517 KB
    snappy-1.1.10              |       h6c2663c_1          92 KB
    sniffio-1.3.0              |   py39haa95532_0          17 KB
    soupsieve-2.5              |   py39haa95532_0          70 KB
    spyder-5.5.1               |   py39haa95532_0        10.4 MB
    spyder-kernels-2.5.0       |   py39haa95532_0         153 KB
    sqlalchemy-2.0.25          |   py39h2bbff1b_0         3.1 MB
    statsmodels-0.14.0         |   py39h9128911_0         9.9 MB
    sympy-1.12                 |   py39haa95532_0        10.5 MB
    tabulate-0.9.0             |   py39haa95532_0          75 KB
    tifffile-2023.4.12         |   py39haa95532_0         403 KB
    tokenizers-0.15.1          |   py39h49fca51_0         1.8 MB
    tornado-6.3.3              |   py39h2bbff1b_0         638 KB
    transformers-4.37.2        |   py39haa95532_0         7.6 MB
    twisted-23.10.0            |   py39haa95532_0         5.4 MB
    typing-extensions-4.9.0    |   py39haa95532_1          10 KB
    typing_extensions-4.9.0    |   py39haa95532_1          54 KB
    tzdata-2024a               |       h04d1e81_0         116 KB
    urllib3-1.26.18            |   py39haa95532_0         198 KB
    w3lib-2.1.2                |   py39haa95532_0          36 KB
    wheel-0.41.2               |   py39haa95532_0         126 KB
    widgetsnbextension-4.0.10  |   py39haa95532_0         949 KB
    xz-5.4.6                   |       h8cc25b3_0         587 KB
    yapf-0.40.2                |   py39haa95532_0         399 KB
    yarl-1.9.3                 |   py39h2bbff1b_0         109 KB
    zeromq-4.3.5               |       hd77b12b_0         5.2 MB
    zfp-1.0.0                  |       hd77b12b_0         242 KB
    zict-3.0.0                 |   py39haa95532_0          91 KB
    zipp-3.17.0                |   py39haa95532_0          23 KB
    ------------------------------------------------------------
                                           Total:       550.4 MB

The following NEW packages will be INSTALLED:

  anaconda-anon-usa~ pkgs/main/win-64::anaconda-anon-usage-0.4.4-py39h8ddfbff_0 None
  aom                pkgs/main/win-64::aom-3.6.0-hd77b12b_0 None
  async-lru          pkgs/main/win-64::async-lru-2.0.4-py39haa95532_0 None
  brotli-python      pkgs/main/win-64::brotli-python-1.0.9-py39hd77b12b_7 None
  dav1d              pkgs/main/win-64::dav1d-1.2.1-h2bbff1b_0 None
  glib-tools         pkgs/main/win-64::glib-tools-2.78.4-hd77b12b_0 None
  gmpy2              pkgs/main/win-64::gmpy2-2.1.2-py39h7f96b67_0 None
  jsonschema-specif~ pkgs/main/win-64::jsonschema-specifications-2023.7.1-py39haa95532_0 None
  jupyter-lsp        pkgs/main/win-64::jupyter-lsp-2.2.0-py39haa95532_0 None
  lazy_loader        pkgs/main/win-64::lazy_loader-0.3-py39haa95532_0 None
  libavif            pkgs/main/win-64::libavif-0.11.1-h2bbff1b_0 None
  libglib            pkgs/main/win-64::libglib-2.78.4-ha17d25a_0 None
  mpc                pkgs/main/win-64::mpc-1.1.0-h7edee0f_1 None
  mpfr               pkgs/main/win-64::mpfr-4.0.2-h62dcd97_1 None
  mpir               pkgs/main/win-64::mpir-3.0.0-hec2e145_1 None
  overrides          pkgs/main/win-64::overrides-7.4.0-py39haa95532_0 None
  pcre2              pkgs/main/win-64::pcre2-10.42-h0ff8eda_0 None
  python-tzdata      pkgs/main/noarch::python-tzdata-2023.3-pyhd3eb1b0_0 None
  referencing        pkgs/main/win-64::referencing-0.30.2-py39haa95532_0 None
  rich               pkgs/main/win-64::rich-13.3.5-py39haa95532_0 None
  rpds-py            pkgs/main/win-64::rpds-py-0.10.6-py39h062c2fa_0 None
  safetensors        pkgs/main/win-64::safetensors-0.4.2-py39h0010962_0 None

The following packages will be REMOVED:

  abseil-cpp-20211102.0-hd77b12b_0
  aiofiles-22.1.0-py39haa95532_0
  aiosqlite-0.18.0-py39haa95532_0
  arrow-cpp-11.0.0-py39h3577439_0
  aws-c-common-0.4.57-ha925a31_1
  aws-c-event-stream-0.1.6-hd77b12b_5
  aws-checksums-0.1.9-ha925a31_0
  aws-sdk-cpp-1.8.185-hd77b12b_0
  boost-cpp-1.73.0-h2bbff1b_12
  brotlipy-0.7.0-py39h2bbff1b_1003
  c-ares-1.19.0-h2bbff1b_0
  clyent-1.2.2-py39haa95532_1
  datasets-2.12.0-py39haa95532_0
  datashape-0.5.4-py39haa95532_1
  gflags-2.2.2-ha925a31_0
  glog-0.5.0-hd77b12b_0
  ipython_genutils-0.2.0-pyhd3eb1b0_1
  jinja2-time-0.2.0-pyhd3eb1b0_3
  jupyter_server_fileid-0.9.0-py39haa95532_0
  jupyter_server_ydoc-0.8.0-py39haa95532_1
  jupyter_ydoc-0.2.4-py39haa95532_0
  jxrlib-1.1-he774522_2
  libboost-1.73.0-h6c2663c_12
  libevent-2.1.12-hcc03200_0
  libllvm14-14.0.6-h4157e71_3
  libprotobuf-3.20.3-h23ce68f_0
  libthrift-0.15.0-he49ee6e_2
  libuv-1.44.2-h2bbff1b_0
  libwebp-1.2.4-hbc33d0d_1
  lz4-4.3.2-py39h2bbff1b_0
  multiprocess-0.70.14-py39haa95532_0
  nbclassic-0.5.5-py39haa95532_0
  ninja-1.10.2-haa95532_5
  ninja-base-1.10.2-h6d14046_5
  orc-1.7.4-h623e30f_1
  pathlib-1.0.1-pyhd3eb1b0_1
  pcre-8.45-hd77b12b_0
  pooch-1.4.0-pyhd3eb1b0_0
  poyo-0.5.0-pyhd3eb1b0_0
  pyarrow-11.0.0-py39haa45b5f_0
  pyrsistent-0.18.0-py39h196d8e1_0
  python-xxhash-2.0.2-py39h2bbff1b_1
  pytorch-2.0.1-cpu_py39hb0bdfb8_0
  qtwebkit-5.212-h2bbfb41_5
  re2-2022.04.01-hd77b12b_0
  responses-0.13.3-pyhd3eb1b0_0
  sacremoses-0.0.43-pyhd3eb1b0_0
  tk-8.6.12-h2bbff1b_0
  toml-0.10.2-pyhd3eb1b0_0
  utf8proc-2.6.1-h2bbff1b_0
  xxhash-0.8.0-h2bbff1b_3
  y-py-0.5.9-py39hb6bf4ef_0
  ypy-websocket-0.8.2-py39haa95532_0

The following packages will be UPDATED:

  aiobotocore                          2.5.0-py39haa95532_0 --> 2.7.0-py39haa95532_0 None
  aiohttp                              3.8.3-py39h2bbff1b_0 --> 3.9.3-py39h2bbff1b_0 None
  anaconda-client                     1.11.3-py39haa95532_0 --> 1.12.3-py39haa95532_0 None
  anyio                                3.5.0-py39haa95532_0 --> 4.2.0-py39haa95532_0 None
  astropy                                5.1-py39h080aedc_0 --> 5.3.4-py39h9128911_0 None
  async-timeout                        4.0.2-py39haa95532_0 --> 4.0.3-py39haa95532_0 None
  attrs                               22.1.0-py39haa95532_0 --> 23.1.0-py39haa95532_0 None
  autopep8                               1.6.0-pyhd3eb1b0_1 --> 2.0.4-pyhd3eb1b0_0 None
  black                               23.3.0-py39haa95532_0 --> 23.11.0-py39haa95532_0 None
  bokeh                                3.1.1-py39h9909e9c_0 --> 3.3.4-py39h9909e9c_0 None
  botocore                           1.29.76-py39haa95532_0 --> 1.31.64-py39haa95532_0 None
  bottleneck                           1.3.5-py39h080aedc_0 --> 1.3.7-py39h9128911_0 None
  bzip2                                    1.0.8-he774522_0 --> 1.0.8-h2bbff1b_5 None
  c-blosc2                                 2.8.0-hd77b12b_0 --> 2.12.0-h2f4ed9d_0 None
  ca-certificates                     2023.05.30-haa95532_0 --> 2024.3.11-haa95532_0 None
  certifi                           2023.5.7-py39haa95532_0 --> 2024.2.2-py39haa95532_0 None
  cffi                                1.15.1-py39h2bbff1b_3 --> 1.16.0-py39h2bbff1b_0 None
  click                                8.0.4-py39haa95532_0 --> 8.1.7-py39haa95532_0 None
  colorcet                             3.0.1-py39haa95532_0 --> 3.1.0-py39haa95532_0 None
  comm                                 0.1.2-py39haa95532_0 --> 0.2.1-py39haa95532_0 None
  conda-package-han~                   2.1.0-py39haa95532_0 --> 2.2.0-py39haa95532_0 None
  conda-package-str~                   0.8.0-py39haa95532_0 --> 0.9.0-py39haa95532_0 None
  conda-repo-cli                      1.0.41-py39haa95532_0 --> 1.0.88-py39haa95532_0 None
  constantly         pkgs/main/noarch::constantly-15.1.0-p~ --> pkgs/main/win-64::constantly-23.10.4-py39haa95532_0 None
  contourpy                            1.0.5-py39h59b6b97_0 --> 1.2.0-py39h59b6b97_0 None
  cookiecutter       pkgs/main/noarch::cookiecutter-1.7.3-~ --> pkgs/main/win-64::cookiecutter-2.6.0-py39haa95532_0 None
  cssselect          pkgs/main/noarch::cssselect-1.1.0-pyh~ --> pkgs/main/win-64::cssselect-1.2.0-py39haa95532_0 None
  curl                                     8.1.1-h2bbff1b_1 --> 8.5.0-he2ea4bf_0 None
  cytoolz                             0.12.0-py39h2bbff1b_0 --> 0.12.2-py39h2bbff1b_0 None
  dal                               2023.1.1-h59b6b97_48681 --> 2023.1.1-h59b6b97_48682 None

In [10]:
pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in c:\users\91799\anaconda3\lib\site-packages (0.10.1)
Requirement already satisfied: numpy>=1.17.3 in c:\users\91799\anaconda3\lib\site-packages (from imbalanced-learn) (1.26.3)
Requirement already satisfied: scipy>=1.3.2 in c:\users\91799\anaconda3\lib\site-packages (from imbalanced-learn) (1.11.4)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\91799\anaconda3\lib\site-packages (from imbalanced-learn) (1.3.2)
Requirement already satisfied: joblib>=1.1.1 in c:\users\91799\anaconda3\lib\site-packages (from imbalanced-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\91799\anaconda3\lib\site-packages (from imbalanced-learn) (3.2.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -atplotlib (c:\users\91799\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\91799\anaconda3\lib\site-packages)

In [12]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\91799\anaconda3\lib\site-packages (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in c:\users\91799\anaconda3\lib\site-packages (from scikit-learn) (1.26.3)
Requirement already satisfied: scipy>=1.5.0 in c:\users\91799\anaconda3\lib\site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in c:\users\91799\anaconda3\lib\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\91799\anaconda3\lib\site-packages (from scikit-learn) (3.2.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -atplotlib (c:\users\91799\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\91799\anaconda3\lib\site-packages)