In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv("V2A.csv", usecols=['V2AH01','V2AH02','V2AH03','V2AH04','V2AH05','V2AH06','PublicID'])

C:\Users\91799\AppData\Local\Temp\ipykernel_26512\3052999014.py:4: DtypeWarning: Columns (258,262,266,267,268,269) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("V2A.csv", usecols=['V2AH01','V2AH02','V2AH03','V2AH04','V2AH05','V2AH06','PublicID'])

In [11]:
df = df.dropna()
df = df[df != 'R']

In [12]:
df['V2AH01'] = df['V2AH01'].astype(float)
df['V2AH02'] = df['V2AH02'].astype(float)
df['V2AH03'] = df['V2AH03'].astype(float)
df['V2AH04'] = df['V2AH04'].astype(float)
df['V2AH05'] = df['V2AH05'].astype(float)
df['V2AH06'] = df['V2AH06'].astype(float)

# df['V2AH01'].value_counts()

In [13]:
df

     PublicID  V2AH01  V2AH02  V2AH03  V2AH04  V2AH05  V2AH06
0      00004O     2.0     2.0     2.0     2.0     2.0     2.0
1      00007I     2.0     1.0     2.0     2.0     2.0     2.0
2      00008G     2.0     2.0     2.0     2.0     2.0     2.0
3      00015J     2.0     2.0     2.0     2.0     2.0     2.0
4      00016H     2.0     2.0     2.0     2.0     2.0     2.0
...       ...     ...     ...     ...     ...     ...     ...
8729   17349I     2.0     2.0     2.0     2.0     2.0     2.0
8730   17350A     2.0     2.0     2.0     2.0     2.0     2.0
8731   17351V     2.0     2.0     2.0     2.0     2.0     2.0
8732   17352T     2.0     2.0     2.0     2.0     2.0     2.0
8733   17354P     2.0     2.0     2.0     2.0     2.0     2.0

[8696 rows x 7 columns]

In [14]:
### df['V2AH01'].replace('', np.nan, inplace=True)

In [15]:
df_out = pd.read_csv('outcome.csv',usecols=['PublicID','MH_outcome'])
df = pd.merge(df, df_out, on='PublicID', how='inner')

In [16]:
df = df.dropna()

In [17]:
df.to_csv('drugs_df.csv', index=False)

In [18]:
X = df.drop(['PublicID','MH_outcome'],axis=1)
# y = df['V4AH01']

In [19]:
y = df['MH_outcome']

In [20]:
df_drugs = df
%store df_drugs

Stored 'df_drugs' (DataFrame)

In [21]:
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()

# X_scaled = scaler.fit_transform(X)

# X = pd.DataFrame(X_scaled, columns=X.columns)

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
# from imblearn.over_sampling import SMOTE


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)
# smote = SMOTE(random_state=42)
# X_train, y_train = smote.fit_resample(X_train, y_train)

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Model Coefficients:")
for feature, coef in zip(X.columns, model.coef_[0]):
    print(f"{feature}: {coef}")

Model Coefficients:
V2AH01: -0.14664770760760426
V2AH02: -0.951955826851261
V2AH03: -0.6740053208491747
V2AH04: -0.8862809418786458
V2AH05: -0.5975843476483836
V2AH06: -0.7236260417683263

In [23]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Compute evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
# roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])

# Print the evaluation metrics
print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
# print(f"ROC AUC: {roc_auc:.4f}")

Evaluation Metrics:
Accuracy: 0.6222
Precision: 0.6211
Recall: 0.6222
F1-score: 0.5210

In [28]:
X.describe()

,V2AH01,V2AH02,V2AH03,V2AH04,V2AH05,V2AH06
count,7567.000000,7567.000000,7567.000000,7567.000000,7567.000000,7567.000000
mean,1.940928,1.949121,1.994846,1.999339,1.999339,1.988635
std,0.235776,0.219765,0.071611,0.025699,0.025699,0.106007
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
50%,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
75%,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [30]:
X.eq(1).sum()

V2AH01    447
V2AH02    385
V2AH03     39
V2AH04      5
V2AH05      5
V2AH06     86
dtype: int64